services:
  db:
    image: postgres:16
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./migrations:/migrations

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: on-failure
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nprat96@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    image: cosmtrek/air
    restart: on-failure
    working_dir: /raspberrysour
    ports:
      - 3333:3333
      - 50051:50051
    volumes:
      - ./:/raspberrysour
  
volumes:
  pgadmin-data:
  local_pgdata: